### ISSUE TITLE
Rust Backups | Delete Oxide Plugins

### ISSUE THREAD

**Issue by GameServersHub** [gameserverapp/Platform#306]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
When doing a Rust backup, it doesn't save any of the plugin information. When installing a UMod update, it reinstalls the container and deletes all plugin data. 

**Expected behavior**
The backup files should contain the plugin configuration files for Oxide. When doing a container reinstall, it shouldn't erase the plugins. It should first safely store them in a backup before reinstalling. If users don't have their plugins saved on Github or other remote sources, they lose all progress.

**Comment by mvaessen** [comment]
Hi,

Thanks for reaching out.

GSA will indeed remove any plugins when the server is reinstalled. During the reinstall everything is removed and installed from scratch. The process will restore plugins that were installed via the dashboard, using the uMod website. Anything not registered on uMod should be backed up manually.

All plugin configs managed through GSA are automatically stored and don't require a backup. These will automatically reupload when you start the game server. For configs you maintain manually you may need to create manual backups and restore them after a game server reinstall. 

I will convert this item into a suggestion since it's mostly a request for a missing feature: storing manually uploaded configs to the backups for RUST.
