### ISSUE TITLE
Email loop on plugin update

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#321]
What I know so far.
Foppa's Vote Rewards updated from 2.7 to 3.0 on Sunday at 1:14 PM. Shortly after GSA detected the update.
The plugin was formerly free with an optional license key in the config. It is now a paid only plugin through https://gameservershub.com/forums/resources/foppas-vote-rewards.88/  
I never had the paid plugin. (Not that it should matter. There is not an upgrade path. Just a discount if you contact foppa)
The emails come exactly every 1 hour and 15 minutes. Currently at 38 I believe.
https://dash.gameserverapp.com/cluster/30630 if you need my dashboard info.

**Comment by mvaessen** [comment]
Hi,

I checked the systems and from what I can tell is the issue only happening for this specific plugin. The problems seems to be related to the installation, which is failing. Failing installations with ARK server API plugins are usually caused by the plugin dev not following the required guidelines. 

Since this plugin was updated only a couple days ago, right before the problems started, this is most likely the reason.
I recommend reaching out to the dev and have them make sure the plugins is following the plugin guidelines we put up: https://help.gameserverapp.com/article/217-ark-server-api-developer-guidelines.

Feel free to re-open this issue if it isn't related to the guidelines. Please do make sure to verify yourself whether this is the case when the dev says it is (because it's probably now).
