### ISSUE TITLE
Online Characters more then 6 Days not visible in new widget

### ISSUE THREAD

**Issue by GERDragon** [gameserverapp/Platform#332]
__Please make sure to leave out any sensitive information__!

**Describe the bug**

If I want to display online characters within the last 6 days in the new widget they don't get displayed. On, for example, 1 Day, the current online characters are portrayed. On some occasions, the current online players are shown even on filter for 5 days.

**To Reproduce**
1. Go to your Dashboard
2. Click on Add Widget
3. Chose Widget: Online Characters
4. Set a filter for last 6 days
5. When a player is connected and you don't see a player in the preview then set it to 5 or less to see if its there

You can also save after setting your filter to 6 days and then change it until you see your player. 

**Expected behavior**

I thought that I can see all connected players the last 6 days in this but I learned its only online characters

**Screenshots**
If applicable, could you add screenshots to help explain your problem? __Please make sure to leave out any sensitive information__!

![image](https://user-images.githubusercontent.com/99832504/214829000-7d488e04-a8b5-43c9-ae31-bd9d59de5485.png)
![image](https://user-images.githubusercontent.com/99832504/214829024-dcb90c2e-a68f-48ef-979c-affa19df9d91.png)

**Additional context**

Also described in Discord
https://discord.com/channels/315049169071112193/424240875732860929/1068123502529499158

**Comment by mvaessen** [comment]
Thanks for posting a detailed report, that really helps!

Upon further investigation and looking at the behaviour you describe, I think what may be causing this seemingly weird behaviour is "caching". When you switch to a different time range, the new export is cached.

When using a longer duration `time range` the caching time is also longer. So for a multi-day time range, the cache is refreshed once every X hours or once over day for longer time ranges. To get the most up-to-date information about online players I recommend using the lowest available time range. This will provide you the most accurate data as the caching time will be minimal. For the 15 minute time range the caching time should be 1 minute.

For people stumbling upon this: `Online characters` info is real time. At the moment the `time range` is still listed, even though it is ignored. Other parts of the system are responsible for determining the time to cache, which is why this issue happened. In some future update there will be some updates added that should automatically hide the time range when it's not applicable.

Please re-open the issue if this problem still comes up using a 15 minute time range.
