### ISSUE TITLE
Allow machine IP changes

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#341]
**Describe the issue**
There does not appear to be a way to change the IP of a dediconnect machine.

**Additional context**
There are times where either the machine is moved to a new hosting location or in my case a nominally dynamic IP was good for 2 years till my ISP decided to make tweaks.

**Comment by mvaessen** [comment]
Hi,

This should now be available, via the danger zone section for your machine.
Please do note that it does require you to manually change the passive IP for IIS (windows) or vsftpd (linux). Otherwise you may experience problems with FTP connections (and so will GSA).

Some services may need a reinstall, but for normal usage this most likely isnt needed. 

Let me know if you experience any issues after changing the IP.
