### ISSUE TITLE
Shop packages QoL

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#357]
### Discussed in https://github.com/gameserverapp/Platform/discussions/345

<div type='discussions-op-text'>

<sup>Originally posted by **JXYZP-G** February 12, 2023</sup>
</div>

Todo
- [x] A Custom link when you press "Get Tokens" in the ingame menu.
- [x] Wipe delivery history
- [x] Transfer tokens between player
- [x] Require min. player level (shop packs only)

Ignored:
- Or you can claim 1 shop item for a specific price then locks up till u purchase a support tier. -> can be done with custom roles
- A separate option how how many days before refill  -> this doesn't seem different from currently available options
- Limit it to a fixed amount and after that you have to pay tokens(custom amount) -> out-of-scope

**Comment by JXYZP-G** [comment]
I'm not completely sure if this belongs here. but it has to do with shop it has to do with the variables of ingame command(ark) for example.

GSA Command: `giveitem {gameid} "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalHelmet.PrimalItemArmor_MetalHelmet'" 1 1 5`

I think there should be a option to randomize the quality number(5) in this case. to {quality) and somewhere to configure this that it stays between 5-7.

While writing this Something with custom variables came up in my head. Since maybe you want another quality each item. Its hard to explain i hope you understand something 😂

**Comment by mvaessen** [comment]
This is a development item, which is used to discuss this particular feature. For new suggestions please use Suggestions. There should be a similar item to what you're suggestion on there. You can add your suggestions to the existing topic 👍

**Comment by Decollates** [comment]
A button to “collapse all” sub packs when opening up a collection. 

The ability to create sub packs/collections for “subscriptions”/paid packs.

**Comment by mvaessen** [comment]
i've locked this topic because it was being used to post new idea's. Please post new idea's in the appropriate section
