### ISSUE TITLE
After changing machine IP Some game servers still report the old IP on the connect page

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#366]
Recently changed the IP of my game server.

![image](https://user-images.githubusercontent.com/749937/224518408-cc9b79b5-fa17-4610-8b69-265e01f910f4.png)
The ones in yellow should be offline although I am unsure if they currently suffer from the issue or not. All the rest should be online.

10544 being a server showing offline (Isle in the pic) 
10546 being one that is reporting correctly.

They have had daily restarts since the change a few weeks ago.

**Comment by mvaessen** [comment]
Hi,

Thanks for the report.

I made some changes to clear the cache upon a machine IP change. A work around is `starting` the game server. It doesn't matter whether it was already on or not. If you hit the `start` button for the servers that have issues, it should switch over to the new IP. I tried this on 2 of your game servers, and it worked great!

I wasnt able to run it for all your game servers, due to scheduled actions and some being turned off.
