### ISSUE TITLE
Token Tasks not Respecting Roles 

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#368]
While attempting to set up tasks that would deliver extra tokens to various patreon tier supporters, I ran into an issue where the token delivery action would not respect the restricted role limit and instead gave tokens to all online players. 

Config for the achievement. 
![image](https://user-images.githubusercontent.com/44717221/225186966-8c6c8190-b41a-44da-a954-c78c2bea8fc7.png)

Task history of execution - none of the players in this list have the Supporter role. 
![image](https://user-images.githubusercontent.com/44717221/225187045-113d7ca8-31d8-4df0-bed2-f12e735f8678.png)

List of current Supporters.
![image](https://user-images.githubusercontent.com/44717221/225187348-44649261-6ba8-44ea-8c3a-a461b5637eb3.png)

As I began setting up the rest of the Patreon Tier tasks, they started to pop off too, for the same players, despite none of them having the required roles.
(Hatchling Tier)
![image](https://user-images.githubusercontent.com/44717221/225187803-82fe87cc-f533-4043-b0f0-0cb6b4e61aa7.png)
(Juvie Tier)
![image](https://user-images.githubusercontent.com/44717221/225187870-96efa8fb-78ba-4f69-8d5d-b3902a209174.png)

**Comment by mvaessen** [comment]
Hi,

I think there is a bit of a misunderstanding about how Achievements work.

Achievements don't look at the actions to determine whether the Achievement should be granted/triggered for a user. So the system does not check whether it has specific roles or not, to determine whether it should run an achievement for that player.

If the player meets the requirement for the achievement, it will trigger. You set it to trigger for everyone that played, in total, more than 1 hours. So that will trigger for basically anyone.

I do recommend to check the execution logs for those achievements. There you can see whether the actions sent tokens. Also, I recommend checking the token transactions logs before posting issues. While checking I was not able to find any weirdness.

Please make sure to check delivery / task logs and token transactions
