### ISSUE TITLE
Patreon - Upgrades to Higher Tiers Only Being Partially Completed

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#369]
So - situation is that I had a player increase their patronage to a higher tier, but the actual actions that are supposed to take place when the system recognizes the upgrade did not take place. 

When the system recognizes the user as this tier, this is what actions are supposed to execute.
![image](https://user-images.githubusercontent.com/44717221/225220764-291deabc-8c9d-4951-bd57-dd30e8e02bed.png)

This is the character in question - unfortunately, while my list of subscribers is starting to grow, this is the only example I have, as they are the only one that has increased their Patronage during the month. Here is a list of their roles they have - they still have the Supporter and Hatchling roles, when those should have been removed when they had "stopped" those Patreon tiers. 
![image](https://user-images.githubusercontent.com/44717221/225221860-765a3f62-aa63-4485-886c-e5f9fb7d6ee6.png)

They still have the Supporter and Hatchling roles, when those should have been removed when they had "stopped" those Patreon tiers.
![image](https://user-images.githubusercontent.com/44717221/225222192-440f1bc7-6df3-4edb-87f4-be54c662e2e1.png)
![image](https://user-images.githubusercontent.com/44717221/225222374-79006708-7aca-436d-bea8-415c5c89df5f.png)

And here is the list of their transactions. Note the increase in Patreon tiers: 
![image](https://user-images.githubusercontent.com/44717221/225221954-1816b2cb-0ec0-46b2-8896-cd22942fcc95.png)

In addition, this part of GSA recognizes that Daydreamer is at the Juvie Nycta tier. 
![image](https://user-images.githubusercontent.com/44717221/225227008-93ee9769-d8bc-42ea-8e7c-633678a8e84e.png)

I've also pushed for a few sync attempts through the dashboard, but it doesn't seem to update the aforementioned tasks/triggers.

**Comment by mvaessen** [comment]
Hi,

According to the subscription details, the swap was detected on March 9th.

I always recommend checking the deliveries, because this shows you exactly what happened (and what didnt).
You can find that on the user profile too: https://dash.gameserverapp.com/admintools/accounts/1130fa74-e847-4a72-9f9a-4cdac552d6bc/deliveries

![Daydreamer_-_Players_-_GameServerApp_com](https://user-images.githubusercontent.com/13402423/225260140-915b95a1-a1a9-43d8-9c31-a388d6fddc60.jpg)

Looking at those 2 deliveries I noticed that one was taking away the Hatchling actions and the other one was granting them again. This makes me believe that there may be some sort of bug where it's executing the wrong actions on the second run.

I'll try looking into that this week

**Comment by mvaessen** [comment]
@Decollates Can you check / confirm for me that the person actually swapped their subscription on March 9th?

To rule out any issues on GSA's side, please make sure to check on Patreon.

**Comment by Decollates** [comment]
> @Decollates Can you check / confirm for me that the person actually swapped their subscription on March 9th?
> 
> To rule out any issues on GSA's side, please make sure to check on Patreon.

I was able to confirm that they made the upgrade on the 9th with receipts in their email. 
![69E4337E-CB19-4A35-9439-DFE4490ABA76](https://user-images.githubusercontent.com/44717221/225379483-65cfd608-56aa-42c2-8b9b-5bbe33899026.png)

**Comment by mvaessen** [comment]
Awesome, thanks!

I think I know what happened, but i'm not 100% sure. I just pushed an update that should fix this problem.
We'll probably have to wait for another swap to know for sure.

**Comment by Decollates** [comment]
Okay, thank you!
