### ISSUE TITLE
GSA Launch Script line endings

### ISSUE THREAD

**Issue by meza** [gameserverapp/Platform#445]
I've been trying to use the GSA Launch Script on a Dediconnect ark (linux) server and have been running into the following issue

**Describe the bug**
The line endings in the gsa-connect.sh end up being CRLF which won't work for linux. It causes all sorts of errors but mainly the "unexpected end of file" error.

**To Reproduce**
1. Go to your configuration template with dediconnect
2. Add a custom multiline script
3. Restart your server
4. See the line endings inside the generated gsa-connect.sh
5. Observe that the server doesn't start

**Expected behavior**
Proper line endings depending on the server operating system

**Comment by mvaessen** [comment]
hi,

The error you're seeing is most likely related to the code you enter in that field. I don't think this is related to GSA.

If you do think this is the case, please provide the code you're using and please make sure to Google the error to ensure this is not related to your code.

**Comment by meza** [comment]
Hey, check this out: https://youtu.be/ozaH2rfE_Hs

**Comment by meza** [comment]
Seems like the line endings mess with an if statement. It works for very primitive syntax like 2 echoes in subsequent rows but for anything more complex, there's a risk of breaking.

**Comment by birdman3131** [comment]
Is the host web browser on Windows or Linux?

**Comment by meza** [comment]
I tried it both on windows and macos. Made no difference unfortunately.

**Comment by mvaessen** [comment]
> Hey, check this out: https://youtu.be/ozaH2rfE_Hs

thanks for the detailed info @meza, that really helps understand the problem better. I'll see if i can push a fix for this today

**Comment by mvaessen** [comment]
@meza upon further investigation, l do still think your script is most likely to blame. 
I had no problem booting up my game server using the code below. Screenshot is using the same text editor from your video. The line endings are there but don't cause any problems for me.

<img width="955" alt="Screenshot 2023-05-25 at 10 59 53" src="https://github.com/gameserverapp/Platform/assets/13402423/f0355cd6-2696-427f-82f5-c44f6870e1bc">

![Screenshot 2023-05-25 at 11 00 40](https://github.com/gameserverapp/Platform/assets/13402423/00b390f9-9820-4a0f-8ebd-1c82fb7a5442)

When using a script that I know will cause line ending problems, because the script is incomplete, it doesn't:

<img width="950" alt="Screenshot 2023-05-25 at 11 04 13" src="https://github.com/gameserverapp/Platform/assets/13402423/a5f0ae86-ad44-42e0-ab9e-dc27e5ab7d04">
<img width="609" alt="Screenshot 2023-05-25 at 11 05 45" src="https://github.com/gameserverapp/Platform/assets/13402423/61ad5557-7873-475c-a64e-ff6eac6d62a6">

While I agree the `./gsa-control.sh: line 2: $'\r': command not found` aren't elegant, they don't seem to cause the same breaking issues for me as they do for you.

**Comment by mvaessen** [comment]
I just pushed an update that will ensure any CR characters are removed.

Please let me know whether this solved the problem!

**Comment by meza** [comment]
Yup, this fixed it! I don't think you've tried it with an actual multiline if condition. But it's now working as expected! 🎉

**Comment by mvaessen** [comment]
I think to get it working with the multi line `if` you need to add a `fi;` or something like that to resolve. Either way, problem fixed!

Thanks for reporting back!

**Comment by meza** [comment]
> I think to get it working with the multi line `if` you need to add a `fi;` or something like that to resolve. Either way, problem fixed!
> 
> Thanks for reporting back!

That was the first thing I tried initially, didn't work :)

**Comment by meza** [comment]
I even tried putting it in a single line, making it as simple as possible, etc. I only open bug reports when I've explored all of these :P
