### ISSUE TITLE
Dashboard: Color picker not really "good"

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#465]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Not really a bug, I think, but I want to use the color picker for my dashboard so I have the same color on every widget. If I select it, I can only select a color of the field I'm currently in (see picture) not a color behind the window I select the picker from

**To Reproduce**
Go to Dashboard -> Widget setting -> Color -> Color pick
Press on the pick symbol
see that only in selected window its possible (selected window meaning, the setting window we're currently in)

**Expected behavior**
Settings window closing, "hide", so we're able to select a color behind the window

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/99832504/291c0341-b3c4-4fb1-a93a-9f9768a6f634)

**Additional context**
Maybe I'm not using it right.. That's also highly possible :D

**Comment by mvaessen** [comment]
hi, this is a limitation caused by the browser. GSA uses HTML Color picker (https://www.w3schools.com/colors/colors_picker.asp), which each browser might implement a little bit different. Unfortunately there is no work around for this, other than using a 3rd party color picker to get the color code before setting it. You can then click the "R G B" to switch it to HEX.
