### ISSUE TITLE
HTTP 413 Response

### ISSUE THREAD

**Issue by BrainlessGaming** [gameserverapp/Platform#511]
When uploading my game.ini and gameusersettings.ini to gameserverapp either by beacon's upload or manually setting the text I get a HTTP 413 response error. I'm fairly certain it's because our file sizes are too big but we only did custom drops and have a lot more to go.

![image2](https://github.com/gameserverapp/Platform/assets/10892322/2c23cd4b-d1eb-40f6-89e9-3f9a141712b2)
![image](https://github.com/gameserverapp/Platform/assets/10892322/9c021818-f4b4-4190-a755-d393c0a4e16f)

**Comment by mvaessen** [comment]
Hi,

I've investigated whether increasing the upload limit beyond the existing 10MB limit is feasible. During my tests did I notice that the loading times would increase to levels that are unacceptable.
Because of that am I not going to increase the existing upload limits any further. I recommend reducing your configs to a more manageable size. 

Alternatively am I open to adding a feature allowing you to manually upload the config to the server directly (using Beacon), basically resulting in disabling GSA's config upload. If you like to see this added please post a Suggestion. For now I unfortunately have to disappoint with rejecting this issue.
