### ISSUE TITLE
Scheduled Tasks Disabling Themselves

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#514]
A few tasks that I have set to execute on my servers have a tendency to fail and turn off if even one of the affected servers is offline, which is really inconvenient for me. To note, these tasks have the setting to execute regardless of the server is online or not - if that’s the case, it shouldn’t cause tasks to turn off just because one server is registered offline and can’t receive the commands, right? One example is this task I have: #18376044 , which is meant to keep resetting the time of day for two testing servers so that staff don’t have to be inconvenienced for putting the commands in.

**Comment by mvaessen** [comment]
Thanks for reporting the issue! I'll further investigate when I finished working on the DediConnect QoL update

**Comment by mvaessen** [comment]
Hi, i tested with some tasks on my test setup and noticed that some of the errors are a bit misleading. In the upcoming update this should be improved.

On further inspection was I able to confirm that there was indeed a hidden piece of code checking whether the game server had started. This should be fixed in the upcoming release.

Thanks again for reporting!

**Comment by Decollates** [comment]
Thanks very much!

**Comment by mvaessen** [comment]
hi, the fix is live. Please let me know if the issue was resolved.
