### ISSUE TITLE
Player goes offline automation triggering when player goes online

### ISSUE THREAD

**Issue by pfistdo** [gameserverapp/Platform#628]
I setup join and leave notifications that are broadcasted when a player joins and leaves the server. When I join the server the leave automation triggers too even though I am still online. 
[Ingame notifications](https://cdn.discordapp.com/attachments/1166795937453199410/1181333634083459082/image.png?ex=6580adae&is=656e38ae&hm=30d881928635e6153b7bfbc429e4a61f8ef5cbdd746557b7a8081ca7f9c33a5e&)
[Automation setup](https://cdn.discordapp.com/attachments/1166795937453199410/1181338781018755175/image.png?ex=6580b279&is=656e3d79&hm=6b709822f452abb06a2fa6df1f230296aee48aab49868d62125e23672e8d5d29&)

I am using GSA with a Nitrado server. I believe the issue might be related to my account that shows "Multi (+1)" instead of "EOS" as it does for most other players.

**Comment by mvaessen** [comment]
Hi, thanks for reporting

After investigating am I happy to say that this was a misunderstanding. There is not bug :)
The issue is caused by GSA's system only processing tasks when the player is online. So in this specific situation, people went offline, GSA scheduled the job to run when they come back online and this caused the double "offline" & "online" actions being triggered.

The easy solution is simply enabling "Ignore player status" on the task settings. I only recommend enabling that for the "Character went offline" task.

![Screenshot_2023-12-05_at_11_11_44](https://github.com/gameserverapp/Platform/assets/13402423/f0a7cd4c-e55a-4a61-b47d-fa8296e9a907)
