### ISSUE TITLE
Online Player count for a cluster is inaccurate

### ISSUE THREAD

**Issue by babsgosgens** [gameserverapp/Platform#880]
**Describe the bug**
Dashboard - Time Series: The data for 'Online Players' for an entire cluster is always identical to the data for the highest performing server in the cluster.

**To Reproduce**
1. Go to 'Dashboard'
2. Add a widget
3. Make it a time series
4. Add a row for Online Players for up to four servers in the same cluster (make sure the busiest server is among it)
5. Add one row for Online Players for the entire cluster

**Expected behavior**
The data for Online Players for the entire cluster is identical to the data of the highest performing server in that cluster. I would expect it to be the sum of the Online Players of all servers in the cluster,

**Screenshots**
<img width="1061" alt="image" src="https://github.com/gameserverapp/Platform/assets/1268142/c2e724d8-5d3b-4962-9c31-b1e05d4b6ae9">

**Additional context**
This behaviour is consistent across different time ranges.

**Comment by mvaessen** [comment]
Thanks for the report!

I looked at the code, and while it's been a while since I worked on that, I think what is causing this is that is't currently set to `MAX`, instead of `SUM`. Looking at your example graph, it does indeed match the highest datapoints, so that suggests it's indeed `MAX`.

Before I can change this, I need to investigate the impact

**Comment by mvaessen** [comment]
![Image](https://github.com/user-attachments/assets/e882712b-b98a-4cc6-9008-06f721d57702)

This is now using `SUM` vs `MAX`. This does appear to look more as you'd expect, right?

**Comment by mvaessen** [comment]
This is now live, please let me know if the issue is resolved

**Comment by LimitlessDrag0n** [comment]
Mind if I chime in?
I don't know if this is correct now because I never had 
![image](https://github.com/user-attachments/assets/eb8df5d1-5616-45d0-839a-a4da9d24bc91)
this ammount of players on my cluster at all on one day
not even 
![image](https://github.com/user-attachments/assets/1cd92c69-25a1-4d55-8be6-0e97714e4db9)
It was more accurate before the changes, at least on my end, then now. I guess, it can be in because of my DayZ servers?

I only have 4 players daily playing on my ark servers currently and I freqently check player count. My Max playercount was/is 15 on all servers

**Comment by mvaessen** [comment]
The difference between `SUM` and `MAX` is that `SUM` would sum up all other records, and `MAX` only takes the highest value.

I looked at your dashboard, and checked the graphs but it does seem to show the right `SUM` values.
See the bottom item with the `*`.

That yellow line is probably all characters across all servers![Image](https://github.com/user-attachments/assets/d5bc5b9e-4fb0-47f7-a1eb-483d8e27891f)

**Comment by NobleKangaroo** [comment]
As per our Discord chit chat, there appears to be a side effect that player counts are not being displayed accurately as a result of this change.

Prior to change, player count seemed to be accurate - the count was the total number of players logged in each day.
![Screenshot 2024-10-08 115000](https://github.com/user-attachments/assets/c0bbe526-972d-4fe2-9e5c-ca519d42d94f)

After change, player count seems to be incorrect - the count is in the thousands for a small / medium cluster.
![Screenshot 2024-10-08 115132](https://github.com/user-attachments/assets/25fc1695-0039-4350-81fd-2bd1e51f1a7e)

Expanding the chart out, instead of using a `*` filter, I found that the individual servers are also collecting incorrect counts.
![Screenshot 2024-10-08 121517](https://github.com/user-attachments/assets/f2399b03-60a1-4e48-8dd1-a3fed1713da2)

The above player count exceeds our character count, 172 characters, so numbers in the thousands shouldn't be possible.
![Screenshot 2024-10-08 121632](https://github.com/user-attachments/assets/0ec1dc4b-2001-41dc-8f78-0654d0040571)

**Comment by mvaessen** [comment]
The changes were reverted. I noticed I misunderstood the original request, which referred to cluster data.
The data is back to the previous version, and seems to be alright.

Will look into the cluster data report again

**Comment by NobleKangaroo** [comment]
> The online characters are fixed now, and i fixed a similar issues on the character hours played dataset.
> 
> Please take a look and let me whether it show the right data now

![image](https://github.com/user-attachments/assets/2b411a5a-113b-4e9b-a3d5-ae013d550682)

Looking good again, thank you so much, Max!
