### ISSUE TITLE
Minecraft login provider

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#955]
- [x] prepared code stuff
- [ ] api approval (waiting for Mojang)

### Discussed in https://github.com/gameserverapp/Platform/discussions/640

<div type='discussions-op-text'>

<sup>Originally posted by **mvaessen** December 12, 2023</sup>
<img width="1214" alt="Screenshot 2023-12-12 at 23 30 12" src="https://github.com/gameserverapp/Platform/assets/13402423/770aaa46-9956-43fc-af3d-0ae00502ca7c">

https://wiki.vg/Microsoft_Authentication_Scheme#Authenticate_with_Minecraft</div>

**Comment by mvaessen** [comment]
Currently waiting on getting API approval from Mojang. This may take 4+ weeks

**Comment by RoyalT20** [comment]
Hooray for progress! Understood and thank you. Unlike the posted picture I am not under the impression that there is a separate login for Minecraft any longer as it has all been merged under the umbrella of a user's Microsoft account. You're probably already aware, but just wanted to make sure since the picture is outdated. Thanks for the continued development!

**Comment by mvaessen** [comment]
it will be a separate login option, as shown on the screenshot.

**Comment by mvaessen** [comment]
This is now available
